name: Terraform Init & Plan

on:
  workflow_call:
    inputs:
      backend_file:
        required: true
        type: string
      tfvars_file:
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init -backend-config=${{ inputs.backend_file }}

      - name: Terraform Plan
        run: terraform plan -var-file=${{ inputs.tfvars_file }} -out=tfplan 
        outputs:
          plan-artifact: ${{ steps.upload-artifact.outputs.artifact-path }} # Output the path to the uploaded artifact  