name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform fmt check
        run: terraform fmt -check -recursive
      - name: Terraform validate
        run: terraform validate
      - name: Terraform Lint
        uses: terraform-linters/tflint-action@v1
        