name: Terraform Init & Plan

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
      - name: Terraform Init
        run: terraform init -backend-config=${{ inputs.backend_file }}
      - name: Terraform Plan
        run: terraform plan -var-file=${{ inputs.tfvars_file }} -out=tfplan
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan
    outputs:
      plan-artifact: ${{ steps.upload-artifact.outputs.artifact-path }} # Output the path to the uploaded artifact  