name: Terraform Lint

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
      - name: Terraform Format Check
        run: terraform fmt -check
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Lint
        uses: terraform-linters/tflint-action@v1
        