name: Notify Slack

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          slack-message: ${{ inputs.message }}
          slack-bot-token: ${{ secrets.SLACK_TOKEN }}
          status: ${{ inputs.status }} # "success" or "failure"   