name: Notification

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: echo "${{ inputs.message }}"
